# Generated by Django 2.0.7 on 2018-07-22 16:22

import catalog.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', djongo.models.fields.EmbeddedModelField(model_container=catalog.models.Category, null=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('slug', models.CharField(db_index=True, max_length=200)),
                ('collection', models.CharField(db_index=True, max_length=200, verbose_name='Collection')),
                ('shape', models.CharField(db_index=True, max_length=100, verbose_name='Dress shape')),
                ('style', models.CharField(db_index=True, max_length=100, verbose_name='Dress style')),
                ('fabric', models.CharField(db_index=True, max_length=100, verbose_name='Dress fabric')),
                ('fastener_type', models.CharField(db_index=True, max_length=100, verbose_name='Dress fastener type')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Product image')),
                ('description', models.TextField(blank=True, verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='In stock')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
