# Generated by Django 2.0.7 on 2018-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=200, verbose_name='Client Name')),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('date_of_appoint', models.DateField(blank=True, null=True)),
                ('date_of_wedding', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=200, verbose_name='Client Name')),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
            ],
        ),
    ]
