# Generated by Django 2.0.7 on 2018-08-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180829_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='img_id',
            field=models.IntegerField(default=1, verbose_name='Image num'),
        ),
    ]
