# Generated by Django 2.0.7 on 2018-08-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productimage_img_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d', verbose_name='Product thumbnail'),
        ),
    ]
