# Generated by Django 2.0.7 on 2018-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='brand',
            field=models.CharField(db_index=True, default='Brand', max_length=200, verbose_name='Brand'),
        ),
    ]
