# Generated by Django 2.0.7 on 2018-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_collection_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='brand',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Brand'),
        ),
    ]
